./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h23v04
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h24v04
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h25v03
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h25v05
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h26v03
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h26v05
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h27v04
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h27v06
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h28v06
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h29v06
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h23v05
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h24v05
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h25v04
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h25v06
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h26v04
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h26v06
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h27v05
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h28v05
./spark-submit --class com.terry.app.TSDataToSData /home/terry/jars/ts_process.jar h28v07
